//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPGiaitriviet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogController
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Controller { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
