//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPGiaitriviet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMO
    {
        public long ID { get; set; }
        public string Command_Code { get; set; }
        public string Phone { get; set; }
        public string Service_ID { get; set; }
        public string Request_ID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
